/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./components/**/*.{js,ts,jsx,tsx,mdx}",
        "./app/**/*.{js,ts,jsx,tsx,mdx}",
        "./lib/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                brand: {
                    50: "#f0fdf4",
                    100: "#dcfce7",
                    200: "#bbf7d0",
                    300: "#86efac",
                    400: "#4ade80",
                    500: "#22c55e",
                    600: "#16a34a",
                    700: "#15803d",
                    800: "#166534",
                    900: "#14532d",
                    950: "#052e16",
                },
                gold: {
                    50: "#fffbeb",
                    100: "#fef3c7",
                    200: "#fde68a",
                    300: "#fcd34d",
                    400: "#fbbf24",
                    500: "#f59e0b",
                    600: "#d97706",
                    700: "#b45309",
                    800: "#92400e",
                    900: "#78350f",
                },
                surface: {
                    DEFAULT: "#0a0f0d",
                    light: "#111b14",
                    card: "#162019",
                    border: "#1e3a28",
                },
            },
            fontFamily: {
                sans: ["Inter", "system-ui", "sans-serif"],
                mono: ["JetBrains Mono", "monospace"],
            },
            backgroundImage: {
                "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
                "hero-pattern": "radial-gradient(ellipse at 30% 20%, rgba(34,197,94,0.1) 0%, transparent 50%), radial-gradient(ellipse at 80% 60%, rgba(251,191,36,0.05) 0%, transparent 50%), #0a0f0d",
                "card-shine": "linear-gradient(135deg, rgba(255,255,255,0.04) 0%, transparent 100%)",
            },
            animation: {
                "fade-in": "fadeIn 0.6s ease-in-out",
                "slide-up": "slideUp 0.5s ease-out both",
                "pulse-slow": "pulse 3s ease-in-out infinite",
                "float": "float 5s ease-in-out infinite",
                "shimmer": "shimmer 2s linear infinite",
                "orb": "orbFloat 12s ease-in-out infinite",
                "btn-glow": "btnGlow 2.5s ease-in-out infinite",
                "gradient": "gradientShift 5s linear infinite",
            },
            keyframes: {
                fadeIn: { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
                slideUp: { "0%": { transform: "translateY(20px)", opacity: "0" }, "100%": { transform: "translateY(0)", opacity: "1" } },
                float: { "0%,100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-10px)" } },
                shimmer: { "from": { backgroundPosition: "-200% 0" }, "to": { backgroundPosition: "200% 0" } },
                orbFloat: { "0%,100%": { transform: "translate(0,0) scale(1)" }, "33%": { transform: "translate(30px,-20px) scale(1.05)" }, "66%": { transform: "translate(-20px,15px) scale(0.95)" } },
                btnGlow: { "0%,100%": { boxShadow: "0 0 0 0 rgba(34,197,94,0.4)" }, "50%": { boxShadow: "0 0 16px 4px rgba(34,197,94,0.25)" } },
                gradientShift: { "0%": { backgroundPosition: "0% center" }, "50%": { backgroundPosition: "100% center" }, "100%": { backgroundPosition: "0% center" } },
            },
            boxShadow: {
                "glow-green": "0 0 24px rgba(34,197,94,0.35)",
                "glow-gold": "0 0 24px rgba(251,191,36,0.35)",
                "card": "0 4px 32px rgba(0,0,0,0.5)",
                "card-hover": "0 8px 48px rgba(0,0,0,0.7)",
            },
        },
    },
    plugins: [],
};
