const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
    console.log("🌾 AgriChain — Deploying AgriTrace to Polygon Mumbai...\n");

    // ── Get deployer ──────────────────────────────────────────────────────────
    const [deployer] = await ethers.getSigners();
    console.log(`📬 Deployer address : ${deployer.address}`);
    const balance = await ethers.provider.getBalance(deployer.address);
    console.log(`💰 Deployer balance : ${ethers.formatEther(balance)} MATIC\n`);

    if (balance === 0n) {
        throw new Error("Deployer has no MATIC. Fund your wallet from https://faucet.polygon.technology/");
    }

    // ── Deploy contract ───────────────────────────────────────────────────────
    console.log("🚀 Deploying AgriTrace contract...");
    const AgriTrace = await ethers.getContractFactory("AgriTrace");
    const agriTrace = await AgriTrace.deploy();
    await agriTrace.waitForDeployment();

    const contractAddress = await agriTrace.getAddress();
    console.log(`✅ AgriTrace deployed at: ${contractAddress}`);

    // ── Verify deployment ─────────────────────────────────────────────────────
    const totalBatches = await agriTrace.totalBatches();
    console.log(`📦 Initial batch count: ${totalBatches}`);

    // ── Save deployment info ──────────────────────────────────────────────────
    const deploymentInfo = {
        network: hre.network.name,
        contractAddress: contractAddress,
        deployer: deployer.address,
        deployedAt: new Date().toISOString(),
        blockNumber: (await ethers.provider.getBlockNumber()),
    };

    const deploymentsDir = path.join(__dirname, "../deployments");
    if (!fs.existsSync(deploymentsDir)) {
        fs.mkdirSync(deploymentsDir, { recursive: true });
    }

    const deploymentFile = path.join(deploymentsDir, `${hre.network.name}.json`);
    fs.writeFileSync(deploymentFile, JSON.stringify(deploymentInfo, null, 2));
    console.log(`\n📄 Deployment info saved to: ${deploymentFile}`);

    // ── Update frontend config ────────────────────────────────────────────────
    const frontendConfigPath = path.join(__dirname, "../frontend/lib/contractAddress.ts");
    if (fs.existsSync(path.dirname(frontendConfigPath))) {
        const configContent = `// Auto-generated by deploy.js — DO NOT EDIT MANUALLY
export const CONTRACT_ADDRESS = "${contractAddress}";
export const NETWORK_CHAIN_ID = ${hre.network.config.chainId || 80001};
export const DEPLOYED_AT = "${new Date().toISOString()}";
`;
        fs.writeFileSync(frontendConfigPath, configContent);
        console.log(`🔗 Frontend contract address updated at: ${frontendConfigPath}`);
    }

    console.log("\n✨ Deployment complete!");
    console.log("─────────────────────────────────────────────────────────");
    console.log(`   Contract: ${contractAddress}`);
    console.log(`   Network : ${hre.network.name} (Chain ID: ${hre.network.config.chainId})`);
    console.log(`   Explorer: https://mumbai.polygonscan.com/address/${contractAddress}`);
    console.log("─────────────────────────────────────────────────────────");
    console.log("\n📝 Next steps:");
    console.log("  1. Copy contract address to frontend/.env.local (NEXT_PUBLIC_CONTRACT_ADDRESS)");
    console.log("  2. Verify on Polygonscan: npx hardhat verify --network mumbai", contractAddress);
}

main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error("❌ Deployment failed:", error);
        process.exit(1);
    });
