// Auto-generated by deploy.js — DO NOT EDIT MANUALLY
export const CONTRACT_ADDRESS = "0x5FbDB2315678afecb367f032d93F642f64180aa3";
export const NETWORK_CHAIN_ID = 80001;
export const DEPLOYED_AT = "2026-02-27T08:43:42.594Z";
