// Auto-generated by deploy.js — update after deployment
// Set NEXT_PUBLIC_CONTRACT_ADDRESS in .env.local

export const CONTRACT_ADDRESS =
    process.env.NEXT_PUBLIC_CONTRACT_ADDRESS ||
    "0x0000000000000000000000000000000000000000";

export const NETWORK_CHAIN_ID = 80002; // Polygon Amoy

export const AMOY_PARAMS = {
    chainId: "0x13882",
    chainName: "Polygon Amoy Testnet",
    nativeCurrency: { name: "MATIC", symbol: "MATIC", decimals: 18 },
    rpcUrls: ["https://rpc-amoy.polygon.technology"],
    blockExplorerUrls: ["https://amoy.polygonscan.com/"],
};

export const MUMBAI_PARAMS = {
    chainId: "0x13881",
    chainName: "Polygon Mumbai Testnet",
    nativeCurrency: { name: "MATIC", symbol: "MATIC", decimals: 18 },
    rpcUrls: ["https://rpc-mumbai.maticvigil.com/"],
    blockExplorerUrls: ["https://mumbai.polygonscan.com/"],
};

// ABI — only the functions used by the frontend
export const AGRITRACE_ABI = [
    // createBatch
    {
        inputs: [
            { name: "cropType", type: "string" },
            { name: "origin", type: "string" },
            { name: "quantityKg", type: "uint32" },
            { name: "moisturePercent", type: "uint8" },
            { name: "gradeScore", type: "uint8" },
            { name: "certifications", type: "string" },
            { name: "pesticidesUsed", type: "bool" },
            { name: "ipfsHash", type: "string" },
        ],
        name: "createBatch",
        outputs: [{ name: "", type: "uint256" }],
        type: "function",
        stateMutability: "nonpayable",
    },
    // addUpdate
    {
        inputs: [
            { name: "tokenId", type: "uint256" },
            { name: "status", type: "uint8" },
            { name: "location", type: "string" },
            { name: "notes", type: "string" },
            { name: "ipfsHash", type: "string" },
        ],
        name: "addUpdate",
        outputs: [],
        type: "function",
        stateMutability: "nonpayable",
    },
    // transferBatchOwnership
    {
        inputs: [
            { name: "tokenId", type: "uint256" },
            { name: "newOwner", type: "address" },
        ],
        name: "transferBatchOwnership",
        outputs: [],
        type: "function",
        stateMutability: "nonpayable",
    },
    // getBatch
    {
        inputs: [{ name: "tokenId", type: "uint256" }],
        name: "getBatch",
        outputs: [
            {
                components: [
                    { name: "tokenId", type: "uint256" },
                    { name: "farmer", type: "address" },
                    { name: "cropType", type: "string" },
                    { name: "origin", type: "string" },
                    { name: "harvestTimestamp", type: "uint256" },
                    { name: "quantityKg", type: "uint32" },
                    {
                        name: "quality",
                        type: "tuple",
                        components: [
                            { name: "moisturePercent", type: "uint8" },
                            { name: "gradeScore", type: "uint8" },
                            { name: "certifications", type: "string" },
                            { name: "pesticidesUsed", type: "bool" },
                        ],
                    },
                    { name: "ipfsHash", type: "string" },
                    { name: "exists", type: "bool" },
                ],
                name: "",
                type: "tuple",
            },
        ],
        type: "function",
        stateMutability: "view",
    },
    // getBatchJourney
    {
        inputs: [{ name: "tokenId", type: "uint256" }],
        name: "getBatchJourney",
        outputs: [
            {
                components: [
                    { name: "updatedBy", type: "address" },
                    { name: "status", type: "uint8" },
                    { name: "location", type: "string" },
                    { name: "notes", type: "string" },
                    { name: "ipfsHash", type: "string" },
                    { name: "timestamp", type: "uint256" },
                ],
                name: "",
                type: "tuple[]",
            },
        ],
        type: "function",
        stateMutability: "view",
    },
    // totalBatches
    {
        inputs: [],
        name: "totalBatches",
        outputs: [{ name: "", type: "uint256" }],
        type: "function",
        stateMutability: "view",
    },
    // createProposal
    {
        inputs: [
            { name: "description", type: "string" },
            { name: "durationSeconds", type: "uint256" },
        ],
        name: "createProposal",
        outputs: [{ name: "", type: "uint256" }],
        type: "function",
        stateMutability: "nonpayable",
    },
    // vote
    {
        inputs: [
            { name: "proposalId", type: "uint256" },
            { name: "inFavor", type: "bool" },
        ],
        name: "vote",
        outputs: [],
        type: "function",
        stateMutability: "nonpayable",
    },
    // Events
    {
        anonymous: false,
        inputs: [
            { indexed: true, name: "tokenId", type: "uint256" },
            { indexed: true, name: "farmer", type: "address" },
            { indexed: false, name: "cropType", type: "string" },
            { indexed: false, name: "origin", type: "string" },
            { indexed: false, name: "harvestTimestamp", type: "uint256" },
            { indexed: false, name: "ipfsHash", type: "string" },
        ],
        name: "BatchCreated",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, name: "tokenId", type: "uint256" },
            { indexed: true, name: "updatedBy", type: "address" },
            { indexed: false, name: "newStatus", type: "uint8" },
            { indexed: false, name: "location", type: "string" },
            { indexed: false, name: "timestamp", type: "uint256" },
        ],
        name: "BatchUpdated",
        type: "event",
    },
];

export const BATCH_STATUS_LABELS: Record<number, string> = {
    0: "Harvested",
    1: "Processing",
    2: "In Transit",
    3: "At Warehouse",
    4: "At Retailer",
    5: "Sold",
    6: "Rejected",
};

export const BATCH_STATUS_COLORS: Record<number, string> = {
    0: "#22c55e",   // green
    1: "#3b82f6",   // blue
    2: "#f59e0b",   // amber
    3: "#8b5cf6",   // violet
    4: "#ec4899",   // pink
    5: "#06b6d4",   // cyan
    6: "#ef4444",   // red
};
